Add files via upload

diff --git a/install-nethunter-modified b/install-nethunter-modified
--- a/install-nethunter-modified
+++ b/install-nethunter-modified
@@ -50,8 +50,8 @@ function ask() {
 }
 
 function get_arch() {
-    printf "${blue}[*] Checking your device & termux architecture ...${reset}\n\n"
-    printf "${yellow}[>] Your device architecture is ${green}[$device_arch] ${yellow}[<]\n[>] Your termux architecture is ${green}[$termux_arch] ${yellow}[<]${reset}\n\n"
+    printf "${blue}[*] Checking your device & termux architecture ...${reset}\n"
+    printf "${yellow}[>] Your device architecture is ${green}[$device_arch] ${yellow}[<]\n[>] Your termux architecture is ${green}[$termux_arch] ${yellow}[<]${reset}\n"
     case $termux_arch in
         arm64-v8a|arm64-v8|aarch64|arm64)
             SYS_ARCH=arm64
@@ -76,6 +76,7 @@ function set_strings() {
     IMAGE_NAME=kalifs-${SYS_ARCH}-full.tar.xz
     SHA_NAME=kalifs-${SYS_ARCH}-full.sha512sum
     VOICE_NAME=$PREFIX/bin/kali_voice.tar.xz
+    PHOTO=Al_Amin_Zone.png
     VOICE=/sdcard/kali_voice
     VOICE1=Welcome_to_Kali.wav
     VOICE2=installing_voice.wav
@@ -96,16 +97,32 @@ function set_strings() {
 
 function cleanup_voice_file() {
     printf "${blue}\n[*] Checking voice files...${reset}\n"
-    for f in ${VOICE1} ${VOICE2} ${VOICE3} ${VOICE4} ${VOICE5} ${VOICE6} ${VOICE7} ${VOICE8} ${VOICE9} ${VOICE10} ${VOICE11} ${VOICE12} ${VOICE13} ${VOICE14} ${VOICE15}; do
+    for f in ${PHOTO} ${VOICE1} ${VOICE2} ${VOICE3} ${VOICE4} ${VOICE5} ${VOICE6} ${VOICE7} ${VOICE8} ${VOICE9} ${VOICE10} ${VOICE11} ${VOICE12} ${VOICE13} ${VOICE14} ${VOICE15}; do
         if [ -e ${VOICE}/$f ]; then
-            printf "$f ${yellow}is OK\n${reset}"
+            printf "$f ${yellow}is OK ${green}[√]\n${reset}"
         else
-            printf "$f ${red}Not found\n${reset}"
-            if [ -f ${VOICE_NAME} ]; then
-                rm -f ${VOICE_NAME}
-            fi
+            printf "$f ${red}Not found\n${reset}";KEEP_CLEAN=1
         fi
     done
+    if [ ! -z $KEEP_CLEAN ]; then
+        if [ -f $PREFIX/bin/modified ]; then
+            if [ -f $VOICE_NAME ]; then
+                printf "\n${yellow}[!] Some existing voice files missing.${reset}"
+                if ask "Do you want delete & download a new one?" "Y"; then
+                    rm -f $VOICE_NAME
+                    printf "${red}[x] Voice archive deleted.${reset}\n"
+                fi
+            fi
+        else
+            if [ -d $VOICE ]; then
+                printf "\n${yellow}[!] Some files missing in voice directory.${reset}\n"
+                if ask "Do you want delete and extract newly" "Y"; then
+                    rm -rf $VOICE
+                    printf "${red}[x] Voice directory deleted.${reset}\n"
+                fi
+            fi
+        fi
+    fi
 }
 
 function prepare_fs() {
@@ -133,9 +150,9 @@ function cleanup() {
 }
 
 function setup_storage() {
-    printf "\n${green} Allow the storage permission.${reset}\n"
+    printf "\n${green}";read -p " Allow the storage permission. [Enter]";printf "${reset}\n"
     termux-setup-storage ||:
-    read -p " [#] Check the Termux storage permission. [Enter]"
+    printf "${blue}\n";read -p " [#] Check the Termux storage permission. [Enter]"; printf "${reset}\n"
     echo "check storage" >> /sdcard/.Al-Amin_Zone || {
         printf "\n\n${green} Please send 'y' command & then press 'Enter'.\n\n Or,${reset}\n"
         setup_storage
@@ -189,44 +206,45 @@ function check_dependencies() {
 
 function update() {
     printf "${yellow}Checking update...${reset}\n\n"
-    axel https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/modified &> /dev/null || {
-         printf "${red}ERROR:\n Internet connection failed${reset}\n\n"
+    if [ -f $PREFIX/bin/modified ]; then
+        rm -f $PREFIX/bin/modified
+    fi
+    axel --output=$PREFIX/bin/modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/modified &> /dev/null || {
+         printf "${red}ERROR:\n Internet connection failed${reset}\n"
          return 0
     }
-    mv modified $PREFIX/bin/modified
-    while read line
-    do  case $line in
-            M011)
-                printf "${red}[${green}√${red}] ${yellow}NetHunter installer up to date.${reset}\n\n"
-                ;;
-            *)
-                printf "${yellow}[!] NetHunter installer new update found.${reset}\n\n"
-                if ask "Do you want update the NetHunter installer?" "Y"; then
-                    printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
-                    axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified 2> /dev/null || {
-                         printf "${red}ERROR:\n Failed to Checking install-nethunter-modified update.\n ${yellow}Continuing Anyway...\n${reset}"
-                         return 0
-                    }
-                    mv $PREFIX/bin/install-nethunter-modified install-nethunter-modified
-                    chmod +x install-nethunter-modified
-                    printf "${green}[√] NetHunter installer successfully updated${reset}\n\n"
-                    echo "Again run script ./install-nethunter-modified"
-                    exit
-                fi
-                ;;
-        esac
+    while read line;do case $line in
+        M011)
+            printf "${red}[${green}√${red}] ${yellow}NetHunter installer up to date.${reset}\n"
+            ;;
+        *)
+            printf "${yellow}[!] NetHunter installer new update found.${reset}\n\n"
+            if ask "Do you want update the NetHunter installer?" "N"; then
+                printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
+                axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified 2> /dev/null || {
+                     printf "${red}ERROR:\n Failed to Checking install-nethunter-modified update.\n ${yellow}Continuing Anyway...\n${reset}"
+                     return 0
+                }
+                mv $PREFIX/bin/install-nethunter-modified install-nethunter-modified
+                chmod +x install-nethunter-modified
+                printf "${green}[√] NetHunter installer successfully updated${reset}\n\n"
+                echo "Again run script ./install-nethunter-modified"
+                exit
+            fi
+            ;;
+    esac
     done < $PREFIX/bin/modified
 }
 
 function sound_setup() {
     unset KEEP_TIME
     if [ -f ${CHROOT}/usr/bin/tz ]; then
-        printf "${yellow}[!] Using Pulseaudio...${reset}\n\n"
+        printf "${yellow}[!] Using Pulseaudio...${reset}\n"
         play-audio ${VOICE}/${VOICE10} &> /dev/null ||:
         KEEP_TIME=1
     fi
     if [ -z $KEEP_TIME ]; then
-    printf "\033[1;35m[*] Configuring Pulseaudio...${reset}\n\n"
+    printf "\033[1;35m[*] Configuring Pulseaudio...${reset}\n"
     play-audio ${VOICE}/${VOICE11} &> /dev/null ||:
         DEFAULT_PA=$PREFIX/etc/pulse/default.pa
         cat > $DEFAULT_PA <<- EOF
@@ -481,9 +499,10 @@ function get_voice() {
     fi
     if [ -z $VOICE_FILE ]; then
         rm -rf ${VOICE}
-    printf "${blue}[*] Downloading voice...${reset}\n\n"
+        printf "${red}[x] Voice directory deleted.${reset}\n"
+    printf "${blue}[*] Downloading voice...${reset}\n"
     axel ${EXTRA_ARGS} --alternate --output=${VOICE_NAME} "$VOICE_URL" &> /dev/null || {
-         printf "${red}ERROR:\n Internet connection failed${reset}\n\n"
+         printf "${red}ERROR:\n Internet connection failed${reset}\n"
          return 0
     }
     fi
