Update install-pulseaudio-termux

diff --git a/install-pulseaudio-termux b/install-pulseaudio-termux
--- a/install-pulseaudio-termux
+++ b/install-pulseaudio-termux
@@ -294,18 +294,20 @@ function create_launcher() {
     PA_LAUNCHER=$PREFIX/bin/pa
     cat > $PA_LAUNCHER <<- EOF
 #!/data/data/com.termux/files/usr/bin/bash -e
-pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 || {
+pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &> /dev/null || {
            rm -rf $HOME/install-pulseaudio-termux
-           echo "Problem of Pulseaudio"
-           echo "Again installing packages"
+           echo "\n\033[1;31mProblem of Pulseaudio\033[0m\n\n"
            apt update &> /dev/null
            apt-get update &> /dev/null
            apt upgrade -y
+           echo "Again installing packages"
            apt reinstall pulseaudio -y &> /dev/null ||:
-           apt install axel -y &> /dev/null
-           axel https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-pulseaudio-termux || {
-                echo "Internet connection error"
-                exit
+           pa || {
+              apt install axel -y &> /dev/null
+              axel https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-pulseaudio-termux || {
+                   printf "\n\033[1;31mInternet connection error\033[0m\n\n"
+                   exit
+              }
            }
            chmod +x install-pulseaudio-termux
            ./install-pulseaudio-termux
