Add files via upload

diff --git a/install-nethunter-modified b/install-nethunter-modified
--- a/install-nethunter-modified
+++ b/install-nethunter-modified
@@ -150,28 +150,41 @@ function check_dependencies() {
         fi
     done
     apt upgrade -y
-    rm -rf $PREFIX/bin/modified $PREFIX/bin/001
-    axel --output=$PREFIX/bin/modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/modified || {
-         printf "${red}ERROR:\n Internet connection failed${reset}\n\n"
-         return 0
-    }
-    chmod +x $PREFIX/bin/modified
-    modified
+}
+
+function update() {
+    unset KEEP_MODIFIED
+    if [ -f $PREFIX/bin/modified  ]; then
+        printf "${yellow}Checking update...${reset}\n\n"
+        rm -f $PREFIX/bin/modified
+        KEEP_MODIFIED=1
+    fi
+    if [ -z $KEEP_MODIFIED ]; then
+        axel --output=$ud https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/modified || {
+             printf "${red}ERROR:\n Internet connection failed${reset}\n\n"
+        }
+    fi
+    if [ -f $PREFIX/bin/modified ]; then
+        chmod +x $PREFIX/bin/modified
+        modified
+    fi
     unset KEEP_UPDATE
-    if [ -f $PREFIX/bin/002 ]; then
-        printf "${yellow}[!] NetHunter installer up to date.${reset}\n\n"
+    if [ -f $PREFIX/bin/001 ]; then
+        printf "${green}[√] ${yellow}NetHunter installer up to date.${reset}\n\n"
+        rm -f $PREFIX/bin/001
         KEEP_UPDATE=1
     fi
-    if [ -z KEEP_UPDATE ]; then
+    if [ -z $KEEP_UPDATE ]; then
         printf "${yellow}[!] NetHunter installer new update found${reset}\n\n"
-        echo "Updating NetHunter installer"
+        printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
         axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified || {
              printf "${red}ERROR:\n Failed to Checking install-nethunter-modified update.\n ${yellow}Continuing Anyway...\n${reset}"
-             return 0
         }
         mv $PREFIX/bin/install-nethunter-modified install-nethunter-modified
         chmod +x install-nethunter-modified
+        printf "${green}[√] NetHunter installer successfully updated${reset}\n\n"
         ./install-nethunter-modified
+        exit
     fi
 }
 
@@ -530,9 +543,9 @@ cmdline="proot \\
         --link2symlink \\
         -0 \\
         -r $CHROOT \\
-        -b /sdcard \\
         -b /dev \\
         -b /proc \\
+        -b /sdcard \\
         -b $CHROOT\$home:/dev/shm \\
         -w \$home \\
            /usr/bin/env -i \\
@@ -866,6 +879,8 @@ print_banner
 get_arch
 set_strings
 check_dependencies
+update
+update1
 prepare_fs
 cleanup_voice_file
 get_voice
