Add files via upload

diff --git a/install-nethunter-modified b/install-nethunter-modified
--- a/install-nethunter-modified
+++ b/install-nethunter-modified
@@ -72,22 +72,23 @@ function get_arch() {
 }
 
 function image_strings() {
+    printf "${light_cyan}"
     read -p "$1[⤶] Enter the image you want to install: " REPLY
     case "$REPLY" in
-        1) wimg="full";printf "${green}[√] You have selected NetHunter ${SYS_ARCH} (full)\n" ;;
-        2) wimg="minimal";printf "${green}[√] You have selected NetHunter ${SYS_ARCH} (minimal)\n" ;;
-        3) case ${SYS_ARCH} in
+        1|f*|F*) wimg="full";printf "${green}[√] You have selected ${light_cyan}[${green}'${yellow}NetHunter ${SYS_ARCH} full${green}'${light_cyan}]\n" ;;
+        2|m*|M*) wimg="minimal";printf "${green}[√] You have selected ${light_cyan}[${green}'${yellow}NetHunter ${SYS_ARCH} minimal${green}'${light_cyan}]\n" ;;
+        3|n*|N*) case ${SYS_ARCH} in
                amd64|i386) printf "${red}      [!] NetHunter ${SYS_ARCH} (nano) not found.\n${blue}";image_strings ;;
-               arm64|armhf) wimg="nano";printf "${green}[√] You have selected NetHunter ${SYS_ARCH} (nano)\n" ;;
+               arm64|armhf) wimg="nano";printf "${green}[√] You have selected ${light_cyan}[${green}'${yellow}NetHunter ${SYS_ARCH} nano${green}'${light_cyan}]\n" ;;
            esac ;;
-        *) printf "${yellow}      [#] Please reply serial number.\n${blue}";image_strings ;;
+        *) printf "${yellow}    [#] Reply the image serial number or letters.\n${blue}";image_strings ;;
     esac
 }
 
 function set_strings() {
-    echo "      [1] NetHunter ${SYS_ARCH} (full)"
-    echo "      [2] NetHunter ${SYS_ARCH} (minimal)"
-    echo "      [3] NetHunter ${SYS_ARCH} (nano)"
+    echo "    [1]   NetHunter ${SYS_ARCH} (full)        [f][F]"
+    echo "    [2]   NetHunter ${SYS_ARCH} (minimal)     [m][M]"
+    echo "    [3]   NetHunter ${SYS_ARCH} (nano)        [n][N]"
     image_strings
     CHROOT=kali-${SYS_ARCH}
     IMAGE_NAME=kalifs-${SYS_ARCH}-${wimg}.tar.xz
@@ -112,6 +113,14 @@ function set_strings() {
     VOICE15=*voice15*
 }
 
+function checkup_internet() {
+    printf "\n${blue}[*] Checking internet connection...${reset}\n"
+    wget -qO- https://ipecho.net/plain &> /dev/null || {
+        printf "${red}[×] Internet connection is not ok.${reset}\n"
+        INTERNET=1
+    }
+}
+
 function cleanup_voice_file() {
     printf "${blue}\n[*] Checking voice files...${reset}\n"
     for f in ${PHOTO} ${VOICE1} ${VOICE2} ${VOICE3} ${VOICE4} ${VOICE5} ${VOICE6} ${VOICE7} ${VOICE8} ${VOICE9} ${VOICE10} ${VOICE11} ${VOICE12} ${VOICE13} ${VOICE14} ${VOICE15}; do
@@ -122,19 +131,20 @@ function cleanup_voice_file() {
         fi
     done
     if [ ! -z $KEEP_CLEAN ]; then
-        if [ -f $PREFIX/bin/modified ]; then
+        if [ -z $INTERNET ]; then
             if [ -f $VOICE_NAME ]; then
                 printf "\n${yellow}[!] Some existing voice files missing.${reset}"
                 if ask "Do you want delete & download newly?" "N"; then
                     rm -f $VOICE_NAME
                     printf "${red}[x] Voice archive deleted.${reset}\n"
+                    cleanup_voice_directory
                 else
-                    printf "${light_cyan}[&]        	  【OR】		   [&]${reset}"
+                    printf "${light_cyan}         	    【OR】${reset}"
                     cleanup_voice_directory
                 fi
             fi
         else
-            printf "\n${yellow}[!] Some files missing in voice directory.${reset}"
+            printf "\n${yellow}[!] Some files missing in voice directory.${reset}\n"
             cleanup_voice_directory
         fi
     fi
@@ -150,6 +160,9 @@ function cleanup_voice_directory() {
 }
 
 function prepare_fs() {
+    get_rootfs_sha_verify() {
+    get_rootfs;get_sha;verify_sha
+    }
     unset KEEP_CHROOT
     if [ -d ${CHROOT} ]; then
         if ask "Existing rootfs directory found. Delete and create a new one?" "N"; then
@@ -157,6 +170,15 @@ function prepare_fs() {
         else
             KEEP_CHROOT=1
         fi
+        if [ ! -f ${IMAGE_NAME} ]; then
+            if ask "Do you want download the [${SYS_ARCH}-${wimg}] rootfs?" "N"; then
+                get_rootfs_sha_verify
+            fi
+        else
+            get_rootfs_sha_verify
+        fi
+    else
+        get_rootfs_sha_verify
     fi
 }
 
@@ -212,7 +234,7 @@ function check_dependencies() {
     printf "\033[1;35mapt upgrade starting...${reset}\n"
     apt upgrade -y || {
         printf "\n${red}ERROR: Failed to upgrade packages.\n_______Please check the internet connection.\n\n"
-        read -p "$1[?] Do you want continue any way ??? [y/N] " ANS
+        read -p "$1[?] Do you want continue any way ??? [y/Enter] " ANS
         printf "\n${reset}"
         case "$ANS" in
         *y*|*Y*) echo "Continuing any way.";return 0;;
@@ -225,22 +247,26 @@ function check_update() {
     if [ -f $PREFIX/bin/modified ]; then
         rm -f $PREFIX/bin/modified
     fi
-    if ask "Do you want to check for update?" "N"; then
-    	printf "${yellow}Checking update...${reset}\n\n"
-    	axel --output=$PREFIX/bin/modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/modified &> /dev/null || {
-             printf "${red}ERROR:\n Internet connection failed${reset}\n"
-             return 0
-    	}
-    	while read line;do case $line in
+    checkup_internet
+    if [ -z $INTERNET ]; then
+        printf "${green}[√] Internet connection is ok.${reset}\n"
+        if ask "Do you want to check for update?" "N"; then
+          printf "${yellow}Checking update...${reset}\n\n"
+          axel --output=$PREFIX/bin/modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/modified &> /dev/null || {
+            printf "${red}ERROR:\n Internet connection failed${reset}\n"
+            return 0
+    	  }
+    	  while read line;do case $line in
              M017)
             	KEEP_UPDATED=1
             	;;
              *)
             	KEEP_UPDATE=1
             	;;
-    	esac
-    	done < $PREFIX/bin/modified
-        update
+    	  esac
+    	  done < $PREFIX/bin/modified
+          update
+        fi
     fi
     if [ ! -z $KEEP_UPDATED ]; then
          printf "${red}[${green}✔${red}] ${yellow}NetHunter installer up to date${reset}";read -p " Press 〈ENTER〉 "
@@ -250,7 +276,7 @@ function check_update() {
 function update() {
     if [ ! -z $KEEP_UPDATE ]; then
         printf "${yellow}[≛] NetHunter installer new update found.\n${light_cyan}"
-        read -p "$1[?] Do you want update this?... [y/N] " REPLY;printf "${reset}\n"
+        read -p "$1[?] Do you want update this?... [y/Enter] " REPLY;printf "${reset}\n"
         case $REPLY in
             *y*|*Y*)
                printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
@@ -518,7 +544,6 @@ function get_url() {
 }
 
 function get_rootfs() {
-    cd $HOME
     unset KEEP_IMAGE
     if [ -f ${IMAGE_NAME} ]; then
         if ask "Existing image file found. Delete and download a new one ?" "N"; then
@@ -541,23 +566,24 @@ function get_voice() {
         VOICE_FILE=1
     fi
     if [ -z $VOICE_FILE ]; then
-        rm -rf ${VOICE}
-        printf "${red}[x] Voice directory deleted.${reset}\n"
-    printf "${blue}[*] Downloading voice...${reset}\n"
-    axel ${EXTRA_ARGS} --alternate --output=${VOICE_NAME} "$VOICE_URL" &> /dev/null || {
-         printf "${red}ERROR:\n Internet connection failed${reset}\n"
-         return 0
-    }
+        printf "${blue}[*] Downloading voice...\n"
+        axel ${EXTRA_ARGS} --alternate --output=${VOICE_NAME} "$VOICE_URL" &> /dev/null || {
+          printf "${red}ERROR:\n Internet connection failed${reset}\n"
+          return 0
+        }
+       printf "${green}[√] Successfully downloaded.${reset}\n"
     fi
 }
 
 function get_sha() {
     if [ -z $KEEP_IMAGE ]; then
-        printf "\n${blue}[*] Getting SHA ... ${reset}\n\n"
-        get_url
         if [ -f ${SHA_NAME} ]; then
             rm -f ${SHA_NAME}
         fi
+    fi
+    if [ ! -f ${SHA_NAME} ]; then
+        printf "\n${blue}[*] Getting SHA ... ${reset}\n\n"
+        get_url
         wget ${EXTRA_ARGS} --continue "${SHA_URL}"
     fi
 }
@@ -566,8 +592,14 @@ function verify_sha() {
     if [ -z $KEEP_IMAGE ]; then
         printf "\n${blue}[*] Verifying integrity of rootfs...${reset}\n\n"
         sha512sum -c $SHA_NAME || {
-            printf "${red} Rootfs corrupted. Please run this installer again or download the file manually\n${reset}"
-            exit 1
+            rm -f ${SHA_NAME}
+            if [ -f $PREFIX/bin/${SHA_NAME} ]; then
+                printf "${red} Rootfs corrupted. Please run this installer again or download the file manually\n${reset}"
+                rm -f $PREFIX/bin/${SHA_NAME}
+                exit 1
+            fi
+            echo "Al-Amin Zone" >>$PREFIX/bin/${SHA_NAME}
+            get_sha
         }
     fi
 }
@@ -586,16 +618,14 @@ function extract_rootfs() {
 }
 
 function extract_voice() {
-    unset KEEP_VOICE
-    if [ -d ${VOICE} ]; then
-        KEEP_VOICE=1
-    fi
-    if [ -z $KEEP_VOICE ]; then
-        if ask "Existing voice directory not found. Do you want extract voice?" "N"; then
-           printf "\n${blue}[*] Extracting voice... ${reset}\n\n"
-           cd /sdcard && tar -xf $VOICE_NAME 2> /dev/null || : cd $HOME
-           printf "${yellow}[✔] You have successfully extracted voice${reset}\n\n"
-           play-audio ${VOICE}/${VOICE15} &> /dev/null ||:
+    if [ ! -d ${VOICE} ]; then
+        if [ -f $VOICE_NAME ]; then
+            if ask "Existing voice directory not found. Do you want extract voice?" "N"; then
+                printf "\n${blue}[*] Extracting voice... ${reset}\n\n"
+                tar -xf $VOICE_NAME -C /sdcard 2> /dev/null || :
+                printf "${yellow}[✔] You have successfully extracted voice${reset}\n\n"
+                play-audio ${VOICE}/${VOICE15} &> /dev/null ||:
+            fi
         fi
     else
         printf "${yellow}[!] Using existing voice directory${reset}\n"
@@ -730,7 +760,7 @@ function start-kex() {
         SCREEN=":1"
     fi
     get_gnu
-    export HOME=\${HOME}; export USER=\${USR}; export PULSE_SERVER=127.0.0.1 ; LD_PRELOAD=\${GNU} nohup vncserver \$SCREEN >/dev/null 2>&1 </dev/null
+    export HOME=\${HOME}; export USER=\${USR}; export PULSE_SERVER=127.0.0.1; LD_PRELOAD=\${GNU} nohup vncserver \$SCREEN >/dev/null 2>&1 </dev/null
     starting_kex=1
     return 0
 }
@@ -1010,9 +1040,6 @@ get_voice
 extract_voice
 sound_setup
 prepare_fs
-get_rootfs
-get_sha
-verify_sha
 extract_rootfs
 create_launcher
 cleanup
@@ -1046,6 +1073,6 @@ printf "${green}[+] nethunter -r          # To run NetHunter as root${reset}\n"
 #printf "${green}[+] nethunter -r kex kill # To stop all NetHunter GUI sessions${reset}\n"
 #printf "${green}[+] nethunter -r kex <command> # Run command in NetHunter env as root${reset}\n"
 printf "${green}[+] nh                    # Shortcut for nethunter${reset}\n"
-printf "${green}[+] nh tz  #Time.Zone.Setup> 1st type nh then tz${reset}\n\n"
+printf "${green}[+] nh tz                 #Time Zone Setup${reset}\n\n"
 play-audio ${VOICE}/${VOICE7} &> /dev/null ||:
 play-audio ${VOICE}/${VOICE8} &> /dev/null ||:
