Add files via upload

diff --git a/install-nethunter-modified b/install-nethunter-modified
--- a/install-nethunter-modified
+++ b/install-nethunter-modified
@@ -1,7 +1,7 @@
 #!/data/data/com.termux/files/usr/bin/bash -e
 
 VERSION=2020011601
-MODIFIED="034 04-Aug-2023"
+MODIFIED="035 04-Aug-2023"
 BASE_URL=https://kali.download/nethunter-images/current/rootfs
 VOICE_URL=https://github.com/shahinuralamin/Technical_Shahinur_Al-Amin/releases/download/install-nethunter-modified/kali_voice.tar.xz
 device_arch=$(getprop ro.product.cpu.abi)
@@ -521,7 +521,7 @@ function check_update() {
             return 0
     	  }
     	  while read line;do case $line in
-             M034) KEEP_UPDATED=1 ;;
+             M035) KEEP_UPDATED=1 ;;
              *) KEEP_UPDATE=1 ;;
     	  esac
     	  done < $PREFIX/bin/modified
@@ -1238,9 +1238,9 @@ EOF
 function minimal_nano_gui() {
     clear
     printf "${blue}\n[*] Checking GUI package dependencies...\n"
-    unset dbus-x11 xfce4 xfce4-terminal tigervnc-standalone-server
+    unset dbus-x11 xfce4 xfce4-terminal tigervnc-standalone-server KEEP_TERMINAL
     if [ ! -f ${CHROOT}/usr/bin/dbus-launch ]; then
-        DBUS_X11="dbus-x11"
+        DBUS_X11="dbus-x11";KEEP_TERMINAL=1
     fi
     if [ ! -f ${CHROOT}/usr/bin/startxfce4 ]; then
         echo "    [1] Kali desktop theme 'higher size' [h]"
@@ -1250,15 +1250,15 @@ function minimal_nano_gui() {
         printf "${blue}";read -p "$1 " REPLY
         printf "${reset}"
         case "$REPLY" in
-            1|h) XFCE4="kali-desktop-xfce";;
-            2|l) XFCE4="xfce4";XFCE_TERMINAL="xfce4-terminal";;
+            1|h) XFCE4="kali-desktop-xfce";KEEP_TERMINAL=1;;
+            2|l) XFCE4="xfce4";XFCE_TERMINAL="xfce4-terminal";KEEP_TERMINAL=1;;
             *) kali_theme;;
         esac
         }
         kali_theme
     fi
     if [ ! -f ${CHROOT}/usr/bin/tigervncserver ]; then
-        TIGER_VNC="tigervnc-standalone-server"
+        TIGER_VNC="tigervnc-standalone-server";KEEP_TERMINAL=1
     fi
     printf "\n${blue}[*] Creating network server…${reset}\n"
     cat > ${CHROOT}/etc/resolv.conf <<- EOF
@@ -1289,28 +1289,29 @@ options edns0 trust-ad
 search whitedome.com.au
 EOF
     nh_terminal() {
-    if ask "Do you want install the apt update?" "N"; then
+    if [ ! -z $KEEP_TERMINAL ]; then
+        if ask "Do you want install the apt update?" "N"; then
+            clear
+            echo 'apt updating...........……'
+            $NH_LAUNCHER apt update -y || :
+        fi
         clear
-        echo 'apt updating...........……'
-        $NH_LAUNCHER apt update -y || :
-    fi
-    clear
-    printf "\n${yellow}[+] sudo default kali password is 'kali' ..\n"
-    printf "    ${blue}Example:-\n    ${reset}[sudo] password for kali: ${green}kali\n${light_cyan}[#] Complete packages may take more than half an hour to install.${reset}\n"
-    if ask "Do you want installing any way?" "Y"; then
-        for g in $XFCE4 $XFCE_TERMINAL $DBUS_X11 $TIGER_VNC; do
-            if [ ! -z $g ]; then
-                printf "${green}\n";read -p "Installing ${g}... [Enter] "; printf "${reset}\n"
-                $NH_LAUNCHER sudo apt reinstall -y $g || {
-                    printf "${red}ERROR: Failed to install GUI packages.\n Exiting.\n${reset}"
-                    exit
-                }
-            fi
-        done
-        printf "\n${blue}[*] Configuring VNC startup……${reset}\n"
-        VNC_LAUNCHER=${CHROOT}/home/kali/.vnc/xstartup
-        VNC_SHORTCUT=${CHROOT}/root/.vnc/xstartup
-        cat > $VNC_LAUNCHER <<- EOF
+        printf "\n${yellow}[+] sudo default kali password is 'kali' ..\n"
+        printf "    ${blue}Example:-\n    ${reset}[sudo] password for kali: ${green}kali\n\n${green}Complete packages may take more than half an hour to install.${reset}\n"
+        if ask "Missing some package. Do you want to installing any way?" "Y"; then
+            for g in $XFCE4 $XFCE_TERMINAL $DBUS_X11 $TIGER_VNC; do
+                if [ ! -z $g ]; then
+                    printf "${green}\n";read -p "Installing ${g}... [Enter] "; printf "${reset}\n"
+                    $NH_LAUNCHER sudo apt reinstall -y $g || {
+                        printf "${red}ERROR: Failed to install GUI packages.\n Exiting.\n${reset}"
+                        exit
+                    }
+                fi
+            done
+            printf "\n${blue}[*] Configuring VNC startup……${reset}\n"
+            VNC_LAUNCHER=${CHROOT}/home/kali/.vnc/xstartup
+            VNC_SHORTCUT=${CHROOT}/root/.vnc/xstartup
+            cat > $VNC_LAUNCHER <<- EOF
 #!/bin/sh
 
 #############################
@@ -1342,28 +1343,29 @@ dbus-launch --exit-with-session gnome-session &
 ##          XFCE          ##
 startxfce4
 EOF
-        chmod 700 $VNC_LAUNCHER
-        if [ -L ${VNC_SHORTCUT} ]; then
-        rm -f ${VNC_SHORTCUT}
+            chmod 700 $VNC_LAUNCHER
+            if [ -L ${VNC_SHORTCUT} ]; then
+            rm -f ${VNC_SHORTCUT}
+            fi
+            if [ ! -f ${VNC_SHORTCUT} ]; then
+                ln -s ${VNC_LAUNCHER} ${VNC_SHORTCUT} >/dev/null
+            fi
+            if ask "Do you want install the apt-get update?" "N"; then
+                clear
+                echo 'Installing apt-get update'
+                $NH_LAUNCHER sudo apt-get update -y
+            fi
         fi
-        if [ ! -f ${VNC_SHORTCUT} ]; then
-            ln -s ${VNC_LAUNCHER} ${VNC_SHORTCUT} >/dev/null
-        fi
-        if ask "Do you want install the apt-get update?" "N"; then
-            clear
-             echo 'Installing apt-get update'
-             $NH_LAUNCHER sudo apt-get update -y
-        fi
-        if ask "Do you want install the Parole Media Player?" "N"; then
-             clear
-             echo 'Installing Media Player'
-             $NH_LAUNCHER sudo apt install parole
-        fi
-        if ask "Do you want install the Firefox ESR?" "N";then
-             clear
-             echo 'Installing Firefox browser'
-             $NH_LAUNCHER sudo apt install firefox-esr
-        fi
+    fi
+    if ask "Do you want install the Parole Media Player?" "N"; then
+        clear
+        echo 'Installing Media Player'
+        $NH_LAUNCHER sudo apt install parole
+    fi
+    if ask "Do you want install the Firefox ESR?" "N";then
+        clear
+        echo 'Installing Firefox browser'
+        $NH_LAUNCHER sudo apt install firefox-esr
     fi
     }
     checkup_internet
