Add files via upload

diff --git a/install-pulseaudio-termux b/install-pulseaudio-termux
--- a/install-pulseaudio-termux
+++ b/install-pulseaudio-termux
@@ -1,16 +1,5 @@
 #!/data/data/com.termux/files/usr/bin/bash -e
 
-function ask() {
-    while true; do
-        printf "${light_cyan}\n[?] "
-        read -p "$1 [Enter] " REPLY
-        printf "${reset}"
-        case "$REPLY" in
-            *) return 0 ;;
-        esac
-    done
-}
-
 function check_dependencies() {
     printf "${blue}\n[*] Checking package dependencies...${reset}\n"
     ## Workaround for termux-app issue #1283 (https://github.com/termux/termux-app/issues/1283)
@@ -27,12 +16,21 @@ function check_dependencies() {
             }
         fi
     done
-    apt upgrade -y
+    printf "\033[1;35mapt upgrade starting...\n${reset}"
+    apt upgrade -y || {
+        printf "\n${red}ERROR: Failed to upgrade packages.\n_______Please check the internet connection.\n\n"
+        read -p "$1[?] Do you want continue any way or exit ? [c/E] " ANS
+        printf "\n${reset}"
+        case "$ANS" in
+        c*|C*) echo "Continuing any way.";return 0;;
+        e|E|*) echo "You have successfully loged out.";exit;;
+        esac
+    }
 }
 
 function ad() {
      REQUEST='_____[ Please subscribe my youtube chennel ]_____'
-     CHENNEL='__________[ Technical Shahinur_Al-Amin ]__________'
+     CHENNEL='_________________[ Al-Amin Zone ]_________________'
      for i in {1..66}; do
      echo -ne "\r${yellow}${REQUEST:0:$i}${reset}"
      sleep .03
@@ -45,27 +43,27 @@ function ad() {
 
 function bootstrap_dir() {
     if [ -d $HOME/storage ]; then
-        printf "\u001b[46m${blue}_____[ Please subscribe my youtube chennel ]______\n__________[ Technical Shahinur_Al-Amin ]__________${reset}\n\n"
+        printf "\u001b[46m${blue}_____[ Please subscribe my youtube chennel ]______\n_________________[ Al-Amin Zone ]_________________${reset}\n\n"
     else
-        printf "\u001b[46m${blue}_____[ Please subscribe my youtube chennel ]______\n__________[ Technical Shahinur_Al-Amin ]__________${reset}\n\n"
+        printf "\u001b[46m${blue}_____[ Please subscribe my youtube chennel ]______\n_________________[ Al-Amin Zone ]_________________${reset}\n\n"
         termux-setup-storage
     fi
-    if ask "Continue with welcome voice"; then
-       printf "${yellow}Continuing Anyway${reset}\n\n"
-       check_dependencies
-       mkdir /sdcard/Termux-Bootstrap &> /dev/null || :
-       if [ -f /sdcard/Termux-Bootstrap/welcome.mp3 ];then
-           printf "${green}Welcome to Tecnical Shahinur_Al-Amin${reset}\n\n"
-           play-audio /sdcard/Termux-Bootstrap/welcome.mp3
-       else
-           axel --output=/sdcard/Termux-Bootstrap/welcome.mp3 https://github.com/shahinuralamin/Technical_Shahinur_Al-Amin/releases/download/termux-prefix-switcher/welcome.mp3 &> /dev/null || {
-                printf "${red}E: Internet connection failed ${reset}\n\n"
-                printf "${green}Welcome to Tecnical Shahinur_Al-Amin${reset}\n\n"
-                return 0
-           }
-           printf "${green}Welcome to Tecnical Shahinur_Al-Amin${reset}\n\n"
-           play-audio /sdcard/Termux-Bootstrap/welcome.mp3
-       fi
+    printf "${light_cyan}\n"
+    read -p " Continue with welcome voice.             [Enter]"
+    printf "${yellow} Continuing Anyway...........${reset}\n\n"
+    check_dependencies
+    mkdir /sdcard/Termux-Bootstrap &> /dev/null || :
+    if [ -f /sdcard/Termux-Bootstrap/welcome.mp3 ];then
+        printf "${green}Welcome to Al-Amin Zone${reset}\n\n"
+        play-audio /sdcard/Termux-Bootstrap/welcome.mp3
+    else
+        axel --output=/sdcard/Termux-Bootstrap/welcome.mp3 https://github.com/shahinuralamin/Technical_Shahinur_Al-Amin/releases/download/termux-prefix-switcher/welcome.mp3 &> /dev/null || {
+             printf "${red}E: Internet connection failed ${reset}\n\n"
+             printf "${green}Welcome to Al-Amin Zone${reset}\n\n"
+             return 0
+        }
+        printf "${green}Welcome to Al-Amin Zone${reset}\n\n"
+        play-audio /sdcard/Termux-Bootstrap/welcome.mp3
     fi
 }
 
@@ -331,7 +329,7 @@ function pa_start() {
                pa_start
                exit
     }
-    printf "\n\033[1;31;42m[ Audio streaming recever running on Pulseaudio ]\033[0m\n\n"
+    printf "\n\033[1;31;42m[ Pulseaudio is running... ]\033[0m\n\n"
     printf "\033[1;4;35m…♪…♪…♪…♪[\033[0m  \033[1;3;35mexport PULSE_SERVER=127.0.0.1\033[0m  \033[1;4;35m]…♪…♪…♪…\033[0m\n\n"
     auto-1
 }
@@ -342,7 +340,9 @@ function pa_stop() {
                auto-0
                exit
     }
-    printf "\n\033[1;31;42m[ Pulseaudio streaming recever stoped ]\033[0m\n\n"
+    auto-0
+    printf "\n\033[1;31;42m[ Pulseaudio is stoped. ]\033[0m\n\n"
+    exit
 }
 
 function auto-0() {
@@ -371,8 +371,8 @@ function auto() {
 }
 
 case "\$1" in
-    start) pa_start;;
-    stop) pa_stop;;
+    *start*) pa_start;;
+    *stop*) pa_stop;;
     *) auto;;
 esac
 EOF
@@ -389,7 +389,7 @@ function print_banner() {
     printf "${light_cyan}★  #      #    # #      *     '#  #       Audio  ★\n"
     printf "${light_cyan}★  #      '####' ######  '#####'  ######  Audio  ★\n"
     printf "${light_cyan}★________________________________________________★\n"
-    printf "${light_cyan}★_________[ ${green}Technical Shahinur_Al-Amin ${light_cyan}]_________★\n"
+    printf "${light_cyan}★________________[ ${green}Al-Amin Zone ${light_cyan}]________________★\n"
     printf "${light_cyan}**************************************************${reset}\n\n"
 }
 
