Add files via upload

diff --git a/install-nethunter-modified b/install-nethunter-modified
--- a/install-nethunter-modified
+++ b/install-nethunter-modified
@@ -50,7 +50,7 @@ function ask() {
 }
 
 function get_arch() {
-    printf "${blue}[*] Checking your device & termux architecture ...${reset}\n"
+    printf "${blue}[*] Checking your device & termux architecture ...\n"
     printf "${yellow}[>] Your device architecture is ${green}[$device_arch] ${yellow}[<]\n[>] Your termux architecture is ${green}[$termux_arch] ${yellow}[<]${reset}\n"
     case $termux_arch in
         arm64-v8a|arm64-v8|aarch64|arm64)
@@ -205,23 +205,29 @@ function check_dependencies() {
 }
 
 function check_update() {
-    printf "${yellow}Checking update...${reset}\n\n"
-    if [ -f $PREFIX/bin/modified ]; then
-        rm -f $PREFIX/bin/modified
+    if ask "Do you want to check for update?" "N"; then
+    	printf "${yellow}Checking update...${reset}\n\n"
+    	if [ -f $PREFIX/bin/modified ]; then
+            rm -f $PREFIX/bin/modified
+    	fi
+    	axel --output=$PREFIX/bin/modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/modified &> /dev/null || {
+             printf "${red}ERROR:\n Internet connection failed${reset}\n"
+             return 0
+    	}
+    	while read line;do case $line in
+             M015)
+            	KEEP_UPDATED=1
+            	;;
+             *)
+            	KEEP_UPDATE=1
+            	;;
+    	esac
+    	done < $PREFIX/bin/modified
+        update
     fi
-    axel --output=$PREFIX/bin/modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/modified &> /dev/null || {
-         printf "${red}ERROR:\n Internet connection failed${reset}\n"
-         return 0
-    }
-    while read line;do case $line in
-        M015)
-            printf "${red}[${green}✔${red}] ${yellow}NetHunter installer up to date.${reset}\n"
-            ;;
-        *)
-            KEEP_UPDATE=1
-            ;;
-    esac
-    done < $PREFIX/bin/modified
+    if [ ! -z $KEEP_UPDATED ]; then
+         printf "${red}[${green}✔${red}] ${yellow}NetHunter installer up to date.${reset}";read -p " "
+    fi
 }
 
 function update() {
@@ -231,7 +237,7 @@ function update() {
         case $REPLY in
             *y*|*Y*)
                printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
-               axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified &> /dev/null || {
+               axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified 2> /dev/null || {
                    printf "${red}ERROR:\n Failed to Checking install-nethunter-modified update.\n ${yellow}Continuing Anyway...\n${reset}"
                    return 0
                }
@@ -958,7 +964,6 @@ get_arch
 set_strings
 check_dependencies
 check_update
-update
 prepare_fs
 cleanup_voice_file
 get_voice
