Update install-nethunter-modified

diff --git a/install-nethunter-modified b/install-nethunter-modified
--- a/install-nethunter-modified
+++ b/install-nethunter-modified
@@ -1,6 +1,7 @@
 #!/data/data/com.termux/files/usr/bin/bash -e
 
 VERSION=2020011601
+MODIFIED=001
 BASE_URL=https://kali.download/nethunter-images/current/rootfs
 VOICE_URL=https://github.com/shahinuralamin/Technical_Shahinur_Al-Amin/releases/download/install-nethunter-modified/kali_voice.tar.xz
 USERNAME=kali
@@ -150,8 +151,13 @@ function check_dependencies() {
     done
     apt upgrade -y
     if [ -f install-nethunter-modified ]; then
-        axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified
+        printf "${blue}Checking install-nethunter-modified update...${reset}\n\n"
+        axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified || {
+             printf "${red}ERROR: Failed to Checking install-nethunter-modified update.\n Continuing anyway...\n${reset}"
+             return 1
+        }
         mv $PREFIX/bin/install-nethunter-modified install-nethunter-modified
+        chmod +x install-nethunter-modified
     fi
 }
 
