Add files via upload

diff --git a/install-nethunter-modified b/install-nethunter-modified
--- a/install-nethunter-modified
+++ b/install-nethunter-modified
@@ -87,7 +87,6 @@ function set_strings() {
     VOICE13=Extracting_rootfs.wav
     VOICE14=Using_existing_rootfs_directory.wav
     VOICE15=Extracted.mp3
-    M003=$PREFIX/bin/modified
 }
 
 function cleanup_voice_file() {
@@ -154,9 +153,9 @@ function check_dependencies() {
 }
 
 function update() {
-    rm -f $PREFIX/bin/modified
     unset KEEP_MODIFIED
-    if [ -f $PREFIX/bin/modified  ]; then
+    if [ -f $PREFIX/bin/modified ]; then
+        rm -f $PREFIX/bin/modified
         KEEP_MODIFIED=1
     fi
     if [ -z $KEEP_MODIFIED ]; then
@@ -165,25 +164,24 @@ function update() {
              printf "${red}ERROR:\n Internet connection failed${reset}\n\n"
         }
     fi
-    while read line
-    done < $PREFIX/bin/modified
+    while read line; do M003=$PREFIX/bin/modified; done < $PREFIX/bin/modified;
     unset KEEP_UPDATE
     if [ -f $line ]; then
-         printf "${red}[${green}√${red}] ${yellow}NetHunter installer up to date.${reset}\n\n"
-         KEEP_UPDATE=1
+            printf "${red}[${green}√${red}] ${yellow}NetHunter installer up to date.${reset}\n\n"
+            KEEP_UPDATE=1
     fi
     if [ -z $KEEP_UPDATE ]; then
-         printf "${yellow}[!] NetHunter installer new update found${reset}\n\n"
-         printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
-         axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified || {
-              printf "${red}ERROR:\n Failed to Checking install-nethunter-modified update.\n ${yellow}Continuing Anyway...\n${reset}"
-              return 0
-         }
-         mv $PREFIX/bin/install-nethunter-modified install-nethunter-modified
-         chmod +x install-nethunter-modified
-         printf "${green}[√] NetHunter installer successfully updated${reset}\n\n"
-         ./install-nethunter-modified
-         exit
+          printf "${yellow}[!] NetHunter installer new update found${reset}\n\n"
+          printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
+          axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified || {
+               printf "${red}ERROR:\n Failed to Checking install-nethunter-modified update.\n ${yellow}Continuing Anyway...\n${reset}"
+               return 0
+          }
+          mv $PREFIX/bin/install-nethunter-modified install-nethunter-modified
+          chmod +x install-nethunter-modified
+          printf "${green}[√] NetHunter installer successfully updated${reset}\n\n"
+          ./install-nethunter-modified
+          exit
     fi
 }
 
