Update install-pulseaudio-termux

diff --git a/install-pulseaudio-termux b/install-pulseaudio-termux
--- a/install-pulseaudio-termux
+++ b/install-pulseaudio-termux
@@ -294,26 +294,54 @@ function create_launcher() {
     PA_LAUNCHER=$PREFIX/bin/pa
     cat > $PA_LAUNCHER <<- EOF
 #!/data/data/com.termux/files/usr/bin/bash -e
-cd \${HOME}
-pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &> /dev/null || {
-           printf "\n\033[1;31mProblem of Pulseaudio\033[0m\n\n"
-           apt update &> /dev/null
-           apt-get update &> /dev/null
-           apt upgrade -y
-           echo "Again installing packages"
-           apt reinstall pulseaudio -y &> /dev/null ||:
-           apt install axel -y &> /dev/null
-           axel --output=$HOME/pulseaudioinstaller https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-pulseaudio-termux || {
-                printf "\n\033[1;31mInternet connection error\033[0m\n"
-           }
-           mv pulseaudioinstaller install-pulseaudio-termux
-           chmod +x install-pulseaudio-termux
-           ./install-pulseaudio-termux
-           pa
-           exit
+cd ${HOME}
+
+function pa_start() {
+    pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &> /dev/null || {
+               printf "\n\033[1;31mProblem of Pulseaudio\033[0m\n\n"
+               apt update &> /dev/null
+               apt-get update &> /dev/null
+               apt upgrade -y
+               echo "Again installing packages"
+               apt reinstall pulseaudio -y &> /dev/null ||:
+               apt install axel -y &> /dev/null
+               axel --output=$HOME/pulseaudioinstaller https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-pulseaudio-termux || {
+                    printf "\n\033[1;31mInternet connection error\033[0m\n"
+               }
+               mv pulseaudioinstaller install-pulseaudio-termux
+               chmod +x install-pulseaudio-termux
+               ./install-pulseaudio-termux
+               pa
+               exit
+    }
+    printf "\n\033[1;31;42m[ Audio streaming recever running on Pulseaudio ]\033[0m\n\n"
+    printf "\033[1;4;35m…♪…♪…♪…♪[\033[0m  \033[1;3;35mexport PULSE_SERVER=127.0.0.1\033[0m  \033[1;4;35m]…♪…♪…♪…\033[0m\n\n"
 }
-printf "\n\033[1;31;42m[ Audio streaming recever running on Pulseaudio ]\033[0m\n\n"
-printf "\033[1;4;35m…♪…♪…♪…♪[\033[0m  \033[1;3;35mexport PULSE_SERVER=127.0.0.1\033[0m  \033[1;4;35m]…♪…♪…♪…\033[0m\n\n"
+
+function pa_stop() {
+    pulseaudio --kill &> /dev/null || {
+               printf "\n\033[1;31m[!] Pulseaudio is not running\033[0m\n\n"
+               exit
+    }
+    printf "\n\033[1;31;42m[ Pulseaudio streaming recever stoped ]\033[0m\n\n"
+}
+
+function launcher() {
+    printf "\033[1;32mpulseaudio \033[1;35m"
+    read -p "$1" REPLY
+    printf "\033[0m"
+    case "$REPLY" in
+        start) pa_start;;
+        stop) pa_stop;;
+        *) pa_start
+    esac
+}
+
+case "$1" in
+    start) pa_start;;
+    stop) pa_stop;;
+    *) launcher ;;
+esac
 EOF
     chmod 700 $PA_LAUNCHER
 }
