Update install-pulseaudio-termux

diff --git a/install-pulseaudio-termux b/install-pulseaudio-termux
--- a/install-pulseaudio-termux
+++ b/install-pulseaudio-termux
@@ -34,7 +34,7 @@ function check_dependencies() {
             echo "  $i is OK"
         else
             printf "\033[35;1mInstalling ${i}...${reset}\n"
-            apt reinstall -y $i || {
+            apt install -y $i || {
                 printf "${red}ERROR: Failed to install packages.\n Exiting.\n${reset}"
 	        exit
             }
@@ -66,18 +66,6 @@ function bootstrap_dir() {
            play-audio /sdcard/Termux-Bootstrap/welcome.mp3
        fi
     fi
-}
-
-function cleanup_pulseaudio() {
-    printf "${blue}\n[*] Checking pulseaudio...${reset}\n"
-    for f in $PREFIX/bin/pulseaudio $PREFIX/etc/pulse/default.pa $PREFIX/etc/pulse/daemon.conf $PREFIX/etc/pulse/client.conf $PREFIX/etc/pulse/system.pa; do
-        if [ -f $f ]; then
-            echo "Pulseaudio installed files found"
-        else
-            echo "pulseaudio installed package file not found"
-            rm -rf $PREFIX/bin/pulseaudio $PREFIX/etc/pulse/default.pa $PREFIX/etc/pulse/daemon.conf $PREFIX/etc/pulse/client.conf $PREFIX/etc/pulse/system.pa
-        fi
-    done
 }
 
 function config_pulseaudio() {
@@ -306,7 +294,19 @@ function create_launcher() {
     PA_LAUNCHER=$PREFIX/bin/pa
     cat > $PA_LAUNCHER <<- EOF
 #!/data/data/com.termux/files/usr/bin/bash -e
-pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
+pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 || {
+           rm -rf $HOME/install-pulseaudio-termux
+           echo "Problem of Pulseaudio"
+           echo "Again installing packages"
+           apt install axel -y
+           axel https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-pulseaudio-termux || {
+                echo "Internet connection error"
+                exit
+           }
+           chmod +x install-pulseaudio-termux
+           ./install-pulseaudio-termux
+exit
+}
 printf "\n\033[1;31;42m[ Audio streaming recever running on Pulseaudio ]\n\n\033[0m\033[1;4;35m…♪…♪…♪…♪[\033[0m  \033[1;3;35mexport PULSE_SERVER=127.0.0.1\033[0m  \033[1;4;35m]…♪…♪…♪…\033[0m\n\n"
 EOF
     chmod 700 $PA_LAUNCHER
@@ -338,7 +338,6 @@ light_cyan='\033[1;96m'
 reset='\033[0m'
 
 print_banner
-cleanup_pulseaudio
 bootstrap_dir
 config_pulseaudio
 create_launcher
