Add files via upload

diff --git a/install-nethunter-modified b/install-nethunter-modified
--- a/install-nethunter-modified
+++ b/install-nethunter-modified
@@ -165,25 +165,26 @@ function update() {
              printf "${red}ERROR:\n Internet connection failed${reset}\n\n"
         }
     fi
-    while read line; do echo "Preparing update" done < $PREFIX/bin/modified
-         unset KEEP_UPDATE
-         if [ -f  $line ]; then
-             printf "${red}[${green}√${red}] ${yellow}NetHunter installer up to date.${reset}\n\n"
-             KEEP_UPDATE=1
-         fi
-         if [ -z $KEEP_UPDATE ]; then
-              printf "${yellow}[!] NetHunter installer new update found${reset}\n\n"
-              printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
-              axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified || {
-                   printf "${red}ERROR:\n Failed to Checking install-nethunter-modified update.\n ${yellow}Continuing Anyway...\n${reset}"
-                   return 0
-              }
-              mv $PREFIX/bin/install-nethunter-modified install-nethunter-modified
-              chmod +x install-nethunter-modified
-              printf "${green}[√] NetHunter installer successfully updated${reset}\n\n"
-              ./install-nethunter-modified
-              exit
-         fi
+    while read line
+    done < $PREFIX/bin/modified
+    unset KEEP_UPDATE
+    if [ -f $line ]; then
+         printf "${red}[${green}√${red}] ${yellow}NetHunter installer up to date.${reset}\n\n"
+         KEEP_UPDATE=1
+    fi
+    if [ -z $KEEP_UPDATE ]; then
+         printf "${yellow}[!] NetHunter installer new update found${reset}\n\n"
+         printf "${yellow}[*] Updating NetHunter installer...${reset}\n\n"
+         axel --output=$PREFIX/bin/install-nethunter-modified https://raw.githubusercontent.com/shahinuralamin/Technical_Shahinur_Al-Amin/main/install-nethunter-modified || {
+              printf "${red}ERROR:\n Failed to Checking install-nethunter-modified update.\n ${yellow}Continuing Anyway...\n${reset}"
+              return 0
+         }
+         mv $PREFIX/bin/install-nethunter-modified install-nethunter-modified
+         chmod +x install-nethunter-modified
+         printf "${green}[√] NetHunter installer successfully updated${reset}\n\n"
+         ./install-nethunter-modified
+         exit
+    fi
 }
 
 function sound_setup() {
