Add files via upload

diff --git a/termux-prefix-switcher b/termux-prefix-switcher
--- a/termux-prefix-switcher
+++ b/termux-prefix-switcher
@@ -79,7 +79,11 @@ function check_dependencies() {
             }
         fi
     done
-    apt upgrade -y
+    printf "\033[1;35mapt upgrade starting...\n"
+    apt upgrade -y || {
+        printf "\n${red}ERROR: Failed to upgrade packages.\n_______Please check the internet connection.\n_______Exiting______.\n${reset}"
+        echo "Continue anyway..."
+    }
 }
 
 function bootstrap_dir() {
@@ -93,14 +97,14 @@ function bootstrap_dir() {
         mkdir /sdcard/Termux-Bootstrap
     fi
     if [ -f /sdcard/Termux-Bootstrap/welcome.mp3 ];then
-        printf "${green}Welcome to Tecnical Shahinur_Al-Amin${reset}\n\n"
+        printf "${green}Welcome to Al-Amin Zone${reset}\n\n"
         play-audio /sdcard/Termux-Bootstrap/welcome.mp3
     else
         axel --output=/sdcard/Termux-Bootstrap/welcome.mp3 https://github.com/shahinuralamin/Technical_Shahinur_Al-Amin/releases/download/termux-prefix-switcher/welcome.mp3 &> /dev/null || {
              printf "${red}E: Internet connection error ${reset}\n"
              return 0
         }
-        printf "${green}Welcome to Tecnical Shahinur_Al-Amin${reset}\n\n"
+        printf "${green}Welcome to Al-Amin Zone${reset}\n\n"
         play-audio /sdcard/Termux-Bootstrap/welcome.mp3
     fi
   fi
@@ -154,7 +158,7 @@ function switch() {
             HEIGHT=15
             WIDTH=40
             CHOICE_HEIGHT=4
-            BACKTITLE="Tecnical Shahinur_Al-Amin"
+            BACKTITLE="Al-Amin Zone"
             TITLE="Termux Prefix Switcher (version 1.3)"
             MENU="Cannot Switch Environment: Your device is running in 32-bit"
 
@@ -185,8 +189,13 @@ function switch() {
         printf "${yellow}Termux-Bootstrap directory created${reset}\n\n"
         mkdir /sdcard/Termux-Bootstrap
     fi
-    printf "${yellow}some warning message${reset}\n\n"
-    printf "${green}"
+    printf "${light_cyan}\n"
+    read -p "Some warning message view in press [Enter] $1"
+    printf "${reset}"
+    case $1 in
+        *) ;;
+    esac
+    printf "\n${green}"
     echo "WARNING: You are about to enter the world of 32-bit, here's what you will expect when entering to 32-bit"
     echo "* Inconsistency will occur when running 64-bit on 32-bit environment, in some cases with the preloaded termux-exec library, you can usually unset it"
     echo "* When Running Chromium in 32-bit proot'ed linux environment, expect segmentation failures (even with --no-sandbox) option,"
@@ -400,7 +409,7 @@ function termux_arch() {
     HEIGHT=15
     WIDTH=40
     CHOICE_HEIGHT=4
-    BACKTITLE="Tecnical Shahinur_Al-Amin"
+    BACKTITLE="Al-Amin Zone"
     TITLE="Termux Prefix Switcher (version 1.3)"
     MENU="Your termux current architecture $(uname -m)"
     OPTIONS=(1 "[Home]")
@@ -425,15 +434,15 @@ function prefix() {
     HEIGHT=21
     WIDTH=39
     CHOICE_HEIGHT=4
-    BACKTITLE="Technical Shahinur_Al-Amin"
+    BACKTITLE="Al-Amin Zone"
     TITLE="Termux Prefix Switcher (version 1.3)"
     MENU="See [termux-prefix-switcher help] for more information"
 
-    OPTIONS=(1 "*  Help       *"
-             2 "*  Switch     *"
-             3 "*  Revert     *"
-             4 "*  check-arch *"
-             5 "*  > Exit <   *")
+    OPTIONS=(1 "*  Help        *"
+             2 "*  Switch      *"
+             3 "*  Revert      *"
+             4 "*  Check Arch  *"
+             5 "* <•> Exit <•> *")
 
     CHOICE=$(dialog --clear \
                     --backtitle "$BACKTITLE" \
@@ -472,19 +481,26 @@ function prefix() {
     exit
 }
 
+function excute_bin() {
+    if [ -f $HOME/termux-prefix-switcher ]; then
+         cp $HOME/termux-prefix-switcher $PREFIX/bin/termux-prefix-switcher && chmod +x $PREFIX/bin/termux-prefix-switcher
+         printf "${green}Prefix Switcher Excuted${reset}\n"
+    fi
+}
+
 function print_banner() {
     clear
     printf "${yellow} .#############################################.\n"
-    printf "${yellow}.##'       ${light_cyan}Technical Shahinur_Al-Amin${yellow}        '##.\n"
-    printf "${yellow}##' ${green}888888888888   .d888b.          db       ${yellow} '##\n"
-    printf "${yellow}##  ${green}     88       d88' '88A        d88b      ${yellow}  ##\n"
-    printf "${yellow}##  ${green}     88       888   '88       d8''8b     ${yellow}  ##\n"
-    printf "${yellow}##  ${green}     88        '88b          d8'  '8b    ${yellow}  ##\n"
-    printf "${yellow}##  ${green}     88          '88b.      d8YaaaaY8b   ${yellow}  ##\n"
-    printf "${yellow}##  ${green}     88       88.  '88b    d8''''''''8b  ${yellow}  ##\n"
-    printf "${yellow}##  ${green}     88       V88' .88b   d8'        '8b ${yellow}  ##\n"
-    printf "${yellow}##. ${green}     88        'd888b'   d8'          '8b${yellow} .##\n"
-    printf "${yellow}'##.            ${light_cyan}Creator By Shahinur${yellow}          .##'\n"
+    printf "${yellow}.##'              ${light_cyan}Al-Amin Zone${yellow}               '##.\n"
+    printf "${yellow}##' ${green}         db             88888888888888   ${yellow} '##\n"
+    printf "${yellow}##  ${green}        d88b                      .d8'   ${yellow}  ##\n"
+    printf "${yellow}##  ${green}       d8''8b                   .d8'     ${yellow}  ##\n"
+    printf "${yellow}##  ${green}      d8'  '8b                .d8'       ${yellow}  ##\n"
+    printf "${yellow}##  ${green}     d8YaaaaY8b             .d8'         ${yellow}  ##\n"
+    printf "${yellow}##  ${green}    d8''''''''8b          .d8'           ${yellow}  ##\n"
+    printf "${yellow}##  ${green}   d8'        '8b       .d8'             ${yellow}  ##\n"
+    printf "${yellow}##. ${green}  d8'          '8b      88888888888888   ${yellow} .##\n"
+    printf "${yellow}'##.        ${light_cyan}Creator By Shahinur Al-Amin${yellow}      .##'\n"
     printf "${yellow} '############### ${red}PREFIX-SWITCHER${yellow} #############'${reset}\n\n"
 }
 
@@ -500,7 +516,7 @@ function print_prefix_banner() {
     printf "${light_cyan}★                                               ★\n"
     printf "${light_cyan}★                  [ SWITCHER ]                 ★\n"
     printf "${light_cyan}★_______________________________________________★\n"
-    printf "${light_cyan}★________[ ${green}Technical Shahinur_Al-Alamin ${light_cyan}]_______★\n"
+    printf "${light_cyan}★________________[ ${green}Al-Amin Zone ${light_cyan}]_______________★\n"
     printf "${light_cyan}*************************************************${reset}\n\n"
 }
 
@@ -530,6 +546,7 @@ case "$1" in
 		print_prefix_banner
                 get_version
                 bootstrap_dir
+                excute_bin
                 prefix
 		;;
 esac
